namespace: '{{repl Namespace}}'
resources:
  - ./seldon-core/rendered.yaml
  - ./seldon-core-crd/rendered.yaml
  - ./seldon-deployment-is.yaml
  - ./issue-summarization-ui.yaml

patchesStrategicMerge:
  - patch-statsd-enabled.yaml
