apiVersion: v1
kind: Service
metadata:
  name: seldon-core-ambassador
spec:
  type: LoadBalancer
  ports:
    - $patch: delete
      port: 80
    - $patch: delete
      port: 443
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
